#!/bin/bash
echo "=== Deployment Pre-Check ==="
echo "1. Python availability:"
which python3
python3 --version
echo ""
echo "2. Python packages:"
python3 -c "import swisseph; print('✓ pyswisseph OK')" || echo "✗ pyswisseph MISSING"
echo ""
echo "3. Python scripts:"
ls -lh server/*.py 2>/dev/null || echo "✗ Python scripts not found"
echo ""
echo "4. Node modules:"
[ -d "node_modules" ] && echo "✓ node_modules exists" || echo "✗ node_modules missing"
echo ""
echo "5. Build output:"
ls -lh dist/ 2>/dev/null && ls -lh dist/public/ 2>/dev/null || echo "✗ Build output missing"
echo ""
echo "6. Environment check:"
echo "NODE_ENV: ${NODE_ENV:-not set}"
echo "PORT: ${PORT:-not set}"
echo "DATABASE_URL: ${DATABASE_URL:+SET}" 
echo ""
echo "=== Pre-Check Complete ==="
